### PR TITLE
add more rabbitmq commands

### PR DESCRIPTION
**Pull request by pawel-yesware**
This adds few more rabbitmq commands

rabbitmq:create-user <name> <username> <password>, Create a RabbitMQ user
rabbitmq:delete-user <name> <username>, Delete a RabbitMQ user
rabbitmq:create-vhost <name> <vhost>, Create a RabbitMQ vhost
rabbitmq:delete-vhost <name> <vhost>, Delete a RabbitMQ vhost
rabbitmq:set-permissions <name> <vhost> <username> <conf> <write> <read>, Sets a RabbitMQ permissions for vhost

### CODE REVIEW

**Comment by josegonzalez** [comment]
Wouldn't it be better to do this from outside of the plugin, via some script or something?

**Comment by rafaferrari** [comment]
how can i create user/pass in this plugin?

**Comment by pawel-yesware** [comment]
@josegonzalez i thought that there was a proposal on how to add more commands to a plugin and in this pull i followed the proposal, so now you are saying we don't want more commands in plugin??

@rafaferrari if you get this branch then you use
rabbitmq:create-user <name> <username> <password>                           Create a RabbitMQ user

**Comment by nreilly** [comment]
Would it be possible to add guidance on how to specify a particular vhost is used for RABBITMQ_URL per app?

**Comment by josegonzalez** [comment]
I've thought about this more and this is related to the support for multiple users/databases in a single service. I don't think this is the correct user interface, though the attempt is appreciated (I'll certainly refer to it in the future when implementing this).

**Pull request closed without merging**
